### PR TITLE
Proposal list page

### LINKED ISSUE #14: Create proposals table page
We need to display a table of proposals to users that approximates this mockup:

PDC Data Viewer 01 - Proposals Table

We should feel free to break this task into sub-tasks if necessary. We have already broken out follow-up tasks for [pagination](https://github.com/PhilanthropyDataCommons/data-viewer/issues/15), [sorting](https://github.com/PhilanthropyDataCommons/data-viewer/issues/16), [filtering](https://github.com/PhilanthropyDataCommons/data-viewer/issues/17), or [column customization](https://github.com/PhilanthropyDataCommons/data-viewer/issues/18).

This task depends on #13 for choosing which columns (canonical fields) and in which order we should display.

### PR DESCRIPTION
**Pull request by jasonaowen**
This PR uses some of changes in #46 to add a list page at `/proposals?page=1&count=20` that will retrieve the list of proposals from the API, transform the data, and display it. Clicking on a row will navigate to the proposal detail page.
    
Currently, the API does not provide the necessary details in the proposal list response, so we have to do an N+1 query where we get the details for each proposal in the list. This can take a long time and be a lot of traffic, but until the API offers more information, it's the only thing to do.
    
This has some pagination support, via the `page` and `count` query parameters, like `/proposals?count=25&page=3`. These parameters are passed along to the API. However, because the API also does not return any information about how many proposals or how many pages there are, we cannot use the `<Paginator>` component created in #46, so instead just set the default `count` parameter to be very high. Again, until the API offers more information, the other alternatives lead to a bad user experience.

For now, we are hardcoding a list of field shortnames to show as columns, but the inner `<ProposalListTable>` does not know or care, so we should be well positioned to allow user customization eventually.

The table has a toggle for whether the contents should be displayed wrapped or truncated, and defaults to showing truncated data.

The table also has a non-functional search box to demonstrate eventual intended functionality.

Resolves #14

### CODE REVIEW

**Comment by jasonaowen** [comment]
I configured Keycloak to allow login from the preview domain, so you should be able to see the list of proposals at https://deploy-preview-49--philanthropy-data-commons-viewer.netlify.app/proposals/ . No pagination yet, so if you want the full list add `?count=1000` to the end.

This draft is also not ready because
- linter errors
- clicking a row should go to the detail page instead of logging a message to the console
- needs tests for the data transformation functions
- pagination

**Comment by reefdog** [comment]
@jasonaowen Faaaantastic! Thank you for this. I'm going to add a few more commits to this in the WIP vein, but when you're online later we should decide how to organize this and #47.

**Comment by jasonaowen** [comment]
Rebased onto `main` after merging #47.

**Comment by jasonaowen** [comment]
To run through the list right now:

- [ ] this PR description is far too brief
- [ ] commit history desperately needs revision
- [x] builds on un-merged PRs [Reference: Proposals table list panel and paginator #46](https://github.com/PhilanthropyDataCommons/data-viewer/pull/46) and [Show proposal details #47](https://github.com/PhilanthropyDataCommons/data-viewer/pull/47)
  - #47 has been merged, and I think the tentative plan was always not to merge #46; I'm happy to make that The Plan going forward
- [ ] linter errors
- [x] clicking a row should go to the detail page instead of logging a message to the console
  - @reefdog took care of this!
- [ ] needs tests for the data transformation functions
- [x] ~~pagination~~
  - we're going to add pagination in a later PR, because https://github.com/PhilanthropyDataCommons/service/issues/179 is not complete and we can't really do much until it is

**Comment by reefdog** [comment]
@jasonaowen Would you have time to add the `getValueOfCanonicalField` fallback behavior to the proposal list table as well, for the same three effective fields (org name, org EIN, and proposal name)?

File: src/components/ProposalListTablePanel.tsx [hunk 1]
```diff
@@ -0,0 +1,80 @@
...
+
+  return (
+    <Panel>
+      <PanelHeader>
+        <PanelActions>
+          <input
+            type="text"
+            placeholder="Search…"
+            className="input"
+          />
```
Comment (jasonaowen) [inline src/components/ProposalListTablePanel.tsx:58]: I know that you were instructed to do this, but it feels Not Great - there's no indicator as to why it won't work, and especially if we're going to be handing out logins soon, I feel like this is likely to be distracting. Can we give it a popup or `disable` it or give it a `disabled` search button or something?

Comment (reefdog) [reply src/components/ProposalListTablePanel.tsx:58]: Agree all around. I think Karl's actual suggestion was that, upon submitting, we display a "coming soon" sort of message. I just punted on that complexity.

What about a dreaded `alert()` on submit?

I'm hoping to avoid a submit button until I style one I like (I have Ideas™); do you think just enter-to-submit is sufficient UI, or do we need a stand-in submit button?

File: .storybook/preview.tsx [hunk 2]
```diff
@@ -17,6 +19,13 @@ const preview: Preview = {
       },
     },
   },
+  decorators: [
+    (Story) => (
+      <BrowserRouter>
+        <Story />
+      </BrowserRouter>
```
[the remark this answers is not in the document]
Comment (reefdog) [reply .storybook/preview.tsx:26]: @jasonaowen Ah, that's why all the examples used it! 😆 I thought I was being so clever.

**Comment by jasonaowen** [comment]
> @jasonaowen Would you have time to add the `getValueOfCanonicalField` fallback chain to the proposal list table as well, for the same three effective fields (org name, org EIN, and proposal name)?

Oof, I'm sorry @reefdog, I don't think I'm going to be able to get that in tonight. Now that that new data is loaded, I see why you want it and it makes sense, but while I think I have an approach it's going to be kinda complicated and I'd rather not do that under time pressure. I opened up #67 to track that.

File: src/components/ProposalListTablePanel.tsx (hunk 1 above)
Comment (jasonaowen) [reply src/components/ProposalListTablePanel.tsx:58]: Can you please add that button, then, and squash it into commit 2c425aa? I think that's the last thing this needs!

**Comment by jasonaowen** [comment]
@reefdog okay, I think this is nearly as good as it's going to get! I'd appreciate your help on the search button, but I'll leave that to your discretion - please merge when you're ready!

File: src/components/ProposalListTablePanel.tsx (hunk 1 above)
Comment (reefdog) [reply src/components/ProposalListTablePanel.tsx:58]: On it!

**Review by reefdog — APPROVED** [review]
It was a hard-fought battle, but this is great stuff. 🎉
